project_id = "egjuybvfhxazpvbeaupy"

[functions.send-appointment-email]
verify_jwt = false

[functions.send-status-update-email]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = false

[functions.create-daily-room]
verify_jwt = true

[functions.get-all-users]
verify_jwt = true

[functions.sync-missing-users]
verify_jwt = true
