project_id = "egjuybvfhxazpvbeaupy"

[functions.send-appointment-email]
verify_jwt = false

[functions.send-status-update-email]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = false

[functions.create-daily-room]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.end-daily-call]
verify_jwt = false

[functions.cleanup-ended-calls]
verify_jwt = false

